export enum Race {
  Bajau = "bajau",
  Bidayuh = "bidayuh",
  Bisaya = "bisaya",
  Brunei = "brunei",
  Bugis = "bugis",
  Chinese = "chinese",
  Dusun = "dusun",
  Iban = "iban",
  Indian = "indian",
  Kadayan = "kadayan",
  Kadazan = "kadazan",
  Kelabit = "kelabit",
  Kenyah = "kenyah",
  Malay = "malay",
  Melanau = "melanau",
  Murut = "murut",
  OrangAsli = "orang asli",
  Penan = "penan",
  Suluk = "suluk",
}
